table Fact_ProjectPhase
	lineageTag: ff784367-6850-4ab0-a865-8e803461395c

	column Project_Phase_Key
		dataType: string
		lineageTag: ba652ed2-f19a-4a28-9a8b-342c107f782f
		summarizeBy: none
		sourceColumn: Project_Phase_Key

		annotation SummarizationSetBy = Automatic

	column Project_ID
		dataType: string
		lineageTag: 988b6d26-fa54-4307-a7cd-b6d190597cad
		summarizeBy: none
		sourceColumn: Project_ID

		annotation SummarizationSetBy = Automatic

	column Phase
		dataType: string
		lineageTag: 69186855-67bc-4dff-b2cb-35eee8c3ca48
		summarizeBy: none
		sourceColumn: Phase

		annotation SummarizationSetBy = Automatic

	column Start_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 74c8b5e9-560a-4495-97ee-fe3da619d8c0
		summarizeBy: none
		sourceColumn: Start_Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Planned_End_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: d0c456cf-4850-4300-b6b1-11f1b36978d9
		summarizeBy: none
		sourceColumn: Planned_End_Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Actual_End_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: b349e03e-b892-4d73-be19-043322b4c306
		summarizeBy: none
		sourceColumn: Actual_End_Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Planned_Duration
		dataType: int64
		formatString: 0
		lineageTag: f86056ea-d465-495f-91c7-bf233d9c5701
		summarizeBy: sum
		sourceColumn: Planned_Duration

		annotation SummarizationSetBy = Automatic

	column Actual_Duration
		dataType: int64
		formatString: 0
		lineageTag: b3b911dd-dc72-49c6-a020-e09f62d6b6b4
		summarizeBy: sum
		sourceColumn: Actual_Duration

		annotation SummarizationSetBy = Automatic

	column Planned_Cost
		dataType: int64
		formatString: 0
		lineageTag: f521d09a-8c49-4ce0-ab55-5643f1c06c6a
		summarizeBy: sum
		sourceColumn: Planned_Cost

		annotation SummarizationSetBy = Automatic

	column Actual_Cost
		dataType: int64
		formatString: 0
		lineageTag: e09683ea-9d81-43f1-8313-f9f8133200f7
		summarizeBy: sum
		sourceColumn: Actual_Cost

		annotation SummarizationSetBy = Automatic

	column Planned_Deliverables
		dataType: int64
		formatString: 0
		lineageTag: 719a3ef7-4831-49cf-9f4a-02843c50fdd8
		summarizeBy: sum
		sourceColumn: Planned_Deliverables

		annotation SummarizationSetBy = Automatic

	column Actual_Deliverables
		dataType: int64
		formatString: 0
		lineageTag: 18e686c5-76f8-4436-b58b-9a5183b0ea96
		summarizeBy: sum
		sourceColumn: Actual_Deliverables

		annotation SummarizationSetBy = Automatic

	column Cost_Variance_Pct_Phase =
			
			DIVIDE (
			    Fact_ProjectPhase[Actual_Cost] - Fact_ProjectPhase[Planned_Cost],
			    Fact_ProjectPhase[Planned_Cost]
			)
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: ee37ca39-81af-4c67-bcff-00266b5e0abf
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Duration_Variance_Pct_Phase =
			
			DIVIDE (
			    Fact_ProjectPhase[Actual_Duration] - Fact_ProjectPhase[Planned_Duration],
			    Fact_ProjectPhase[Planned_Duration]
			)
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: 21e59076-f2ae-4f73-a55a-9bbe6f6df749
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Deliverable_Variance_Pct_Phase =
			
			DIVIDE (
			    Fact_ProjectPhase[Actual_Deliverables] - Fact_ProjectPhase[Planned_Deliverables],
			    Fact_ProjectPhase[Planned_Deliverables]
			)
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: d93c4f0b-b344-43af-b2bb-d7d6e1b884cc
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Cost_Alert_Flag =
			
			VAR PlannedCost = Fact_ProjectPhase[Planned_Cost]
			VAR ActualCost = Fact_ProjectPhase[Actual_Cost]
			RETURN
			    IF (
			        PlannedCost > 0
			            && NOT ISBLANK ( ActualCost )
			            && DIVIDE ( ActualCost - PlannedCost, PlannedCost ) >= 15 / 100,
			        1,
			        0
			    )
		formatString: 0
		lineageTag: 1f713d9b-d141-4055-820a-b6684a0b926b
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Duration_Alert_Flag =
			
			VAR PlannedDuration = Fact_ProjectPhase[Planned_Duration]
			VAR ActualDuration = Fact_ProjectPhase[Actual_Duration]
			RETURN
			    IF (
			        PlannedDuration > 0
			            && NOT ISBLANK ( ActualDuration )
			            && DIVIDE (
			                ActualDuration - PlannedDuration,
			                PlannedDuration
			            ) >= 15 / 100,
			        1,
			        0
			    )
		formatString: 0
		lineageTag: 10f28c1d-a8df-49a1-90d6-21b68d3f69af
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Deliverable_Alert_Flag =
			
			VAR PlannedDeliverables = Fact_ProjectPhase[Planned_Deliverables]
			VAR ActualDeliverables = Fact_ProjectPhase[Actual_Deliverables]
			RETURN
			    IF (
			        PlannedDeliverables > 0
			            && NOT ISBLANK ( ActualDeliverables )
			            && DIVIDE (
			                PlannedDeliverables - ActualDeliverables,
			                PlannedDeliverables
			            ) >= 15 / 100,
			        1,
			        0
			    )
		formatString: 0
		lineageTag: 9e24723b-64c7-465f-ba9e-dc8690fe70f5
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Alert_Count = ```
			
			    Fact_ProjectPhase[Cost_Alert_Flag]
			        + Fact_ProjectPhase[Duration_Alert_Flag]
			        + Fact_ProjectPhase[Deliverable_Alert_Flag]
			```
		formatString: 0
		lineageTag: ab1372d1-bb81-4d88-b8f3-ae4d8df62c2b
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Alert_Flag =
			
			IF (
			    Fact_ProjectPhase[Alert_Count] >= 1,
			    1,
			    0
			)
		formatString: 0
		lineageTag: 0e7ce854-420d-4404-9cb6-d2b649069e26
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Alert_Severity =
			
			SWITCH (
			    Fact_ProjectPhase[Alert_Count],
			    3, "Critique",
			    2, "Élevée",
			    1, "À surveiller",
			    "Conforme"
			)
		lineageTag: a979808a-92c0-41a2-9f25-52de467c890c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Deadline_Variance_Days_Phase =
			
			VAR PlannedEndDate = Fact_ProjectPhase[Planned_End_Date]
			VAR ActualEndDate = Fact_ProjectPhase[Actual_End_Date]
			RETURN
			    IF (
			        NOT ISBLANK ( PlannedEndDate )
			            && NOT ISBLANK ( ActualEndDate ),
			        DATEDIFF ( PlannedEndDate, ActualEndDate, DAY ),
			        BLANK ()
			    )
		formatString: 0
		lineageTag: 4e2cf1a4-2179-4fe8-b8c5-b3fc084d9ecb
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Phase_Duration_Status =
			VAR Planned = Fact_ProjectPhase[Planned_Duration]
			VAR Actual = Fact_ProjectPhase[Actual_Duration]
			RETURN
			    SWITCH ( TRUE (),
			        ISBLANK ( Planned ) || Planned <= 0 || ISBLANK ( Actual ) || Actual < 0, "Non évaluable",
			        DIVIDE ( Actual - Planned, Planned ) >= 15 / 100, "Alerte",
			        "Hors alerte"
			    )
		lineageTag: ecccc03c-c6c8-44f4-bf16-ddaa3d3a3417
		summarizeBy: none

	column Phase_Cost_Status =
			VAR Planned = Fact_ProjectPhase[Planned_Cost]
			VAR Actual = Fact_ProjectPhase[Actual_Cost]
			RETURN
			    SWITCH ( TRUE (),
			        ISBLANK ( Planned ) || Planned <= 0 || ISBLANK ( Actual ) || Actual < 0, "Non évaluable",
			        DIVIDE ( Actual - Planned, Planned ) >= 15 / 100, "Alerte",
			        "Hors alerte"
			    )
		lineageTag: bfcf9a98-179a-4a77-bfce-42ff43964ea4
		summarizeBy: none

	column Phase_Deliverable_Status =
			VAR Planned = Fact_ProjectPhase[Planned_Deliverables]
			VAR Actual = Fact_ProjectPhase[Actual_Deliverables]
			RETURN
			    SWITCH ( TRUE (),
			        ISBLANK ( Planned ) || Planned <= 0 || ISBLANK ( Actual ) || Actual < 0, "Non évaluable",
			        DIVIDE ( Actual - Planned, Planned ) <= -15 / 100, "Alerte",
			        "Hors alerte"
			    )
		lineageTag: 93aefb99-4034-4e12-b5a1-a44a08d7f41b
		summarizeBy: none

	partition Fact_ProjectPhase = m
		mode: import
		source =
				let
				    Source = stg_ProjectPlans,
				    MergedCosts = Table.NestedJoin(
				        Source,
				        {"Project_Phase_Key"},
				        stg_ActualCosts,
				        {"Project_Phase_Key"},
				        "ActualCosts",
				        JoinKind.LeftOuter
				    ),
				    ExpandedCosts = Table.ExpandTableColumn(MergedCosts, "ActualCosts", {"Actual_Cost"}, {"Actual_Cost"}),
				    MergedDuration = Table.NestedJoin(
				        ExpandedCosts,
				        {"Project_Phase_Key"},
				        stg_ActualDuration,
				        {"Project_Phase_Key"},
				        "ActualDuration",
				        JoinKind.LeftOuter
				    ),
				    ExpandedDuration = Table.ExpandTableColumn(
				        MergedDuration,
				        "ActualDuration",
				        {"Actual_Duration"},
				        {"Actual_Duration"}
				    ),
				    MergedDeliverables = Table.NestedJoin(
				        ExpandedDuration,
				        {"Project_Phase_Key"},
				        stg_ActualDeliverables,
				        {"Project_Phase_Key"},
				        "ActualDeliverables",
				        JoinKind.LeftOuter
				    ),
				    ExpandedDeliverables = Table.ExpandTableColumn(
				        MergedDeliverables,
				        "ActualDeliverables",
				        {"Actual_Deliverables"},
				        {"Actual_Deliverables"}
				    ),
				    AddedActualEndDate = Table.AddColumn(
				        ExpandedDeliverables,
				        "Actual_End_Date",
				        each Date.AddDays([Start_Date], [Actual_Duration]),
				        type date
				    ),
				    ReorderedColumns = Table.ReorderColumns(
				        AddedActualEndDate,
				        {
				            "Project_Phase_Key",
				            "Project_ID",
				            "Phase",
				            "Start_Date",
				            "Planned_End_Date",
				            "Actual_End_Date",
				            "Planned_Duration",
				            "Actual_Duration",
				            "Planned_Cost",
				            "Actual_Cost",
				            "Planned_Deliverables",
				            "Actual_Deliverables"
				        }
				    )
				in
				    ReorderedColumns

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

